[env:sparkfun_promicrorp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = sparkfun_promicrorp2040
framework = arduino
platform_packages =
  framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#275e73d13e5248418e13507d3988ebbf785cff36
monitor_speed = 115200

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = 
  +<packet_builder.cpp>
  +<command_parser.cpp>
  +<quad_uart_controller.cpp>
  -<main.cpp>
build_flags =
  -std=gnu++17
