[env:sparkfun_promicrorp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = sparkfun_promicrorp2040
framework = arduino
monitor_speed = 115200
build_flags =
  -DUSE_TINYUSB
  -I$PROJECT_PACKAGES_DIR/framework-arduinopico/libraries/Adafruit_TinyUSB_Arduino/src/arduino
