[env:sparkfun_promicrorp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = sparkfun_promicrorp2040
framework = arduino
platform_packages =
  framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#275e73d13e5248418e13507d3988ebbf785cff36
extra_scripts =
  pre:scripts/apply_framework_patches.py
monitor_speed = 115200
build_flags =
  -DUSE_TINYUSB
  -I$PROJECT_PACKAGES_DIR/framework-arduinopico/libraries/Adafruit_TinyUSB_Arduino/src/arduino
